services:
  bd:
    image: mysql:8.0
    container_name: bd
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  web:
    build: ./web
    container_name: web
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_NAME: prueba
      DB_PASSWORD: pass
    depends_on:
      bd:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", mysqladmin ping -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always

volumes:
  db_data: